In [2]:
!pip install numpy
import numpy as np

###Question 1

In [3]:
#Create a 1D array from 5 to 20
array_1D = np.arange(5, 21)
print(array_1D)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


###Question 2

In [4]:
#Extract all even numbers from array
even_numbers = array_1D[array_1D % 2 == 0]
print(even_numbers)

[ 6  8 10 12 14 16 18 20]


###Question 3

In [5]:
#Replace all odd numbers in array with 0 using conditions
array_1D[array_1D % 2 != 0] = 0
print(array_1D)

[ 0  6  0  8  0 10  0 12  0 14  0 16  0 18  0 20]


###Question 4

In [6]:
#Create a 3 by 4 NumPy array of all False's
false_array = np.full((3,4), False)
print(false_array)

[[False False False False]
 [False False False False]
 [False False False False]]


###Question 5

In [7]:
#Convert array_1D into a 2D array with 2 rows
array_2D = array_1D.reshape(2, -1)
print(array_2D)

[[ 0  6  0  8  0 10  0 12]
 [ 0 14  0 16  0 18  0 20]]


###Question 6

In [8]:
#Common items between arrays
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([7,2,10,3,4,9,10,8])
common_items = np.intersect1d(arr1, arr2)
print(common_items)

[2 3 4 7]


###Question 7

In [9]:
#Get all items between 5 and 10 from arr
arr = np.array([2,6,1,9,10,3,27])
arr_filter = arr[(arr >= 5) & (arr <= 10)]
print(arr_filter)

[ 6  9 10]


###Question 8

In [10]:
#Using random to create an array with floats between 6 and 12
Random_Array = np.random.randint(6, 12, (3,4))
print(Random_Array)

[[10  9 11  8]
 [ 7  9  7 11]
 [ 9 11 11  7]]


###Question 9 and 10

In [11]:
#Create and sort an array of integers
#Sort a 1D array
New_Array = np.array([9, 10, 22, 75, 74, 37, 18, 98])
sort_array = np.sort(New_Array)
print(sort_array)

#sort descending
sorted_array = np.sort(New_Array)[::-1]
print(sorted_array)

[ 9 10 18 22 37 74 75 98]
[98 75 74 37 22 18 10  9]


In [13]:
#Wanted to test out sorting a 2 by 4 array
New_2D_Array = np.array([[9, 10, 22, 75], [74, 37, 18, 98]])
array_Sort = np.sort(New_2D_Array)
print(sorted_array)

#sort descending
Desc_sorted_array = np.sort(New_2D_Array)[:,::-1]
print(Desc_sorted_array)

[98 75 74 37 22 18 10  9]
[[75 22 10  9]
 [98 74 37 18]]
